Draft: Split modules, update readme
T-Systems-MMS/falcon-eye-monitoring pull request #16
Opened 2023-02-03 08:34 UTC by ronnyfriedland

2023-02-03 14:29 UTC, 2Fraennk commented
Got this error when building and starting F.E.M. base:
`
⠧ Container fem_prometheus           Starting                                                                                       0.7s
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/docker/falcon-eye-monitoring/target/config/prometheus.yml" to rootfs at "/etc/prometheus/prometheus.yml": mount /opt/docker/falcon-eye-monitoring/target/config/prometheus.yml:/etc/prometheus/prometheus.yml (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
make: *** [Makefile.fem:19: start] Error 1
`

Suggest try to change the path inside the volume mount of prometheus docker-compose like this:
"
volumes:
      - $PWD/target/fem/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - "

2023-02-03 14:30 UTC, 2Fraennk commented
Got this error when building the fem-demoapp:
`
make --file Makefile.fem-demoapp start
docker-compose --file target/demoapp/docker-compose-fem-demoapp.yml up -d
ERROR: .NotADirectoryError: [Errno 20] Not a directory: './target/demoapp/docker-compose-fem-demoapp.yml'
make: *** [Makefile.fem-demoapp:11: start] Error 1
`

2023-02-03 18:43 UTC, ronnyfriedland commented
Fixed paths for FEM (core) .

2023-02-03 18:44 UTC, ronnyfriedland commented
Cannot reproduce demoapp problem

2023-02-06 10:44 UTC, 2Fraennk commented
Container for tel-collector doesn't start: config -files were not found:
```fem_otel-collector:
    image: otel/opentelemetry-collector-contrib:0.63.1
    container_name: fem_otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - $PWD/target/config/otel-collector-fem-config.yml:/etc/otel-collector-config.yml:ro
      - $PWD/target/certs:/tmp/certs:ro

origin-path should be: 
- $PWD/target/fem/config/otel-collector-fem-config.yml:/etc/otel-collector-config.yml:ro
- $PWD/target/fem/certs:/tmp/certs:ro

2023-02-06 10:46 UTC, 2Fraennk commented
Container for loki doesn't start: config -files is not found:

```fem_loki:
    image: grafana/loki:main
    container_name: fem_loki
    command: -config.file=/etc/loki/config.yml
    volumes:
      - $PWD/target/config/loki-config.yml:/etc/loki/config.yml:ro

origin path should be:  - $PWD/target/fem/config/loki-config.yml:/etc/loki/config.yml:ro

2023-02-06 10:53 UTC, 2Fraennk commented
Plz add "Configuration / Preparation" for the make-config-step as headline to the Readme.md to the section "DB Exporters", like: https://github.com/T-Systems-MMS/falcon-eye-monitoring#configuration--preparation

2023-02-06 11:02 UTC, 2Fraennk reviewed
After building the image for demoapp, it's name is "demoapp_fem_demoapp", see:
"CONTAINER ID   IMAGE                                               COMMAND                  CREATED              STATUS                          PORTS                                                                    NAMES
2dd6118e53c6   demoapp_fem_demoapp                                 "/usr/local/bin/mvn-…"   About a minute ago   Up About a minute               0.0.0.0:38080->8080/tcp, :::38080->8080/tcp                              fem_demoapp"
double mention of demoapp?

2023-02-06 11:04 UTC, 2Fraennk commented
> Cannot reproduce demoapp problem

Same for me, it works now.

2023-02-06 11:17 UTC, 2Fraennk requested changes
"@cp shellexporter/docker-compose-fem-shellexporter.yml target" should be:
"@cp shellexporter/docker-compose-fem-shellexporter.yml target/shellexporter"

2023-02-06 11:25 UTC, 2Fraennk requested changes
Makefile.fem-shellexporter should looks like that?
"SHELL := /bin/bash

prepare-fem-shellexporter:
        @cp -rn shellexporter target
        @cp shellexporter/docker-compose-fem-shellexporter.yml target/shellexporter
..."

2023-02-06 11:27 UTC, 2Fraennk requested changes
"docker-compose-fem-shellexporter.yml" should change it's context like this?
"...
context: .
..."

2023-02-14 09:24 UTC, 2Fraennk requested changes
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on Makefile.fem
> +	docker-compose --file target/fem/docker-compose-fem.yml up -d
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on Makefile.fem-dbexporter
> +	docker-compose --file target/dbexporter/docker-compose-fem-dbexporter-postgresql.yml up -d
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on Makefile.fem-dbexporter
> +	docker-compose --file target/dbexporter/docker-compose-fem-dbexporter-mongodb.yml up -d
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on Makefile.fem-demoapp
> +	docker-compose --file target/demoapp/docker-compose-fem-demoapp.yml up -d
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on Makefile.fem-shellexporter
> +	docker-compose --file target/shellexporter/docker-compose-fem-shellexporter.yml up -d
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on dbexporter/docker-compose-fem-dbexporter-mongodb.yml
>        - fem_monitoring
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on dbexporter/docker-compose-fem-dbexporter-mongodb.yml
> -    networks:
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on dbexporter/docker-compose-fem-dbexporter-postgresql.yml
> +      - fem_monitoring
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on dbexporter/docker-compose-fem-dbexporter-postgresql.yml
> +  fem_monitoring:
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on demoapp/docker-compose-fem-demoapp.yml
>    fem_demoapp:
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on fem/docker-compose-fem.yml
>        - fem_monitoring
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on fem/docker-compose-fem.yml
> +      - fem_monitoring
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on fem/docker-compose-fem.yml
>        - fem_monitoring
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on fem/docker-compose-fem.yml
>        - fem_monitoring
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-14 09:24 UTC, 2Fraennk commented on fem/docker-compose-fem.yml
>        - fem_monitoring
@ronnyfriedland , I think the definition of the project name is needed now, e.g. add: "--project-name fem".
With the separation into modules it must be ensure that all components run in the same network.
As you know without configure the project name, the name for the container as well as the name for the network were created from the directory name by default. That results into different subnets for the containers. The avoid that we have to set the project name and remove the "fem_"-prefix in all docker-compose files.

2023-02-16 10:47 UTC, 2Fraennk requested changes
just one more to go  ;)
https://github.com/T-Systems-MMS/falcon-eye-monitoring/pull/16/files#r1105514012

2023-02-16 11:18 UTC, ronnyfriedland commented
added missing project parameter to mongodb exporter

2023-02-16 12:23 UTC, 2Fraennk approved these changes

2023-02-16 12:59 UTC, merged